spring.application.name=backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/rf2_prototype}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:rf2_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:rf2_dev_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.session.jdbc.initialize-schema=never

